"""empty message

Revision ID: 0a5c25740c54
Revises: d6c4185d36f3
Create Date: 2022-09-03 09:12:14.528785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5c25740c54'
down_revision = 'd6c4185d36f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('styles_id', sa.Integer(), nullable=False),
    sa.Column('experts_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experts_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['styles_id'], ['styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'styles_id', 'experts_id', 'user_id')
    )
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('favourites')
    # ### end Alembic commands ###
