"""empty message

Revision ID: 193238b223a8
Revises: fa225a07d999
Create Date: 2022-11-08 15:09:06.325229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193238b223a8'
down_revision = 'fa225a07d999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('publish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publish_id'], ['publish.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('publish', 'files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish', sa.Column('files', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('file')
    # ### end Alembic commands ###
