"""empty message

Revision ID: 264dffad20a1
Revises: ed3d41d3ce35
Create Date: 2022-10-15 19:58:07.464857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264dffad20a1'
down_revision = 'ed3d41d3ce35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experts', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experts', type_='foreignkey')
    op.drop_column('experts', 'user_id')
    # ### end Alembic commands ###
