"""empty message

Revision ID: 347cb4217f64
Revises: 8b224233326d
Create Date: 2022-10-16 20:10:45.348430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347cb4217f64'
down_revision = '8b224233326d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
