"""empty message

Revision ID: 3e602b5a1317
Revises: 28af24917ae1
Create Date: 2022-08-30 14:41:01.604900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e602b5a1317'
down_revision = '28af24917ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=200), nullable=False),
    sa.Column('information', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style')
    )
    op.add_column('user', sa.Column('username', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_table('styles')
    # ### end Alembic commands ###
