"""empty message

Revision ID: 5450335fcb30
Revises: 0a5c25740c54
Create Date: 2022-09-03 09:22:41.579133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5450335fcb30'
down_revision = '0a5c25740c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
