"""empty message

Revision ID: 864728430aa5
Revises: d0e96dd307a7
Create Date: 2022-08-30 19:18:44.086789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864728430aa5'
down_revision = 'd0e96dd307a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=200), nullable=False),
    sa.Column('information', sa.String(length=2000), nullable=False),
    sa.Column('image', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('styles')
    # ### end Alembic commands ###
