"""empty message

Revision ID: d0e96dd307a7
Revises: e975b8baf2e1
Create Date: 2022-08-30 19:17:33.614040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e96dd307a7'
down_revision = 'e975b8baf2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('styles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('style', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('information', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='styles_pkey'),
    sa.UniqueConstraint('style', name='styles_style_key')
    )
    # ### end Alembic commands ###
