"""empty message

Revision ID: e975b8baf2e1
Revises: 3e602b5a1317
Create Date: 2022-08-30 17:36:43.025599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e975b8baf2e1'
down_revision = '3e602b5a1317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('styles', sa.Column('image', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('styles', 'image')
    # ### end Alembic commands ###
